version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "rust"
    schedule:
      interval: "daily"
    groups:
      all-rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "typescript/scamplers-frontend"
    schedule:
      interval: "daily"
    groups:
      all-typescript-dependencies:
        patterns:
          - "*"
