repos:
  - repo: local
    hooks:
      - id: check-rust
        name: Check Rust Code
        entry: ./scripts/check-rust.sh
        language: script
        pass_filenames: false
      - id: build-scamplers-core
        name: Build scamplers-core
        entry: ./scripts/build-scamplers-core.sh
        language: script
        pass_filenames: false
      - id: check-typescript
        name: Check TypeScript Code
        entry: ./scripts/check-typescript.sh
        language: script
        pass_filenames: false
      - id: check-sql
        name: Check SQL Code
        entry: ./scripts/check-sql.sh
        language: script
        pass_filenames: false
