# TODO: the same alpine version is used twice - we can fix this somehow
services:
  postgres:
    image: postgres:17-alpine3.21
    restart: always
    user: root
    secrets:
      - db_root_user
      - db_root_password
      - db_name
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_root_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    expose:
      - &db_port 5432
    healthcheck:
      test: pg_isready --dbname $(cat /run/secrets/db_name) || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
  scamplers-backend:
    restart: always
    build:
      args:
        RUST_VERSION: 1.86
      context: .
      dockerfile: rust/Dockerfile
      target: final
    environment:
      PORT: &backend_port 8000
      DB_HOST: &db_host postgres
      DB_PORT: *db_port
      PUBLIC_URL: ${SCAMPLERS_PUBLIC_URL}
    expose:
      - *backend_port
    secrets:
      - source: db_root_user
        uid: "10001"
      - source: db_root_password
        uid: "10001"
      - source: db_login_user_password
        uid: "10001"
      - source: db_auth_user_password
        uid: "10001"
      - source: db_name
        uid: "10001"
      - source: seed_data
        uid: "10001"
    volumes:
      - logs:/logs
      - scamplers-frontend:/opt/scamplers-frontend
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      # TODO: interpolate backend_port
      test: curl http://localhost:8000/health || exit 1
      interval: 5s
      start_period: 10s
      start_interval: 1s
      timeout: 5s
      retries: 10
  scamplers-auth:
    restart: always
    build:
      args:
        PYTHON_VERSION: 3.13
      context: python/scamplers-auth
      target: final
    depends_on:
      scamplers-backend:
        condition: service_healthy
    environment:
      PORT: &auth_port 8000
      DB_HOST: *db_host
      DB_PORT: *db_port
      BACKEND_HOST: &backend_host scamplers-backend
      BACKEND_PORT: *backend_port
      AUTH_SUBDOMAIN: &auth_subdomain auth
      PUBLIC_URL: ${SCAMPLERS_PUBLIC_URL}
      MS_AUTH_PATH: &ms_auth_path /microsoft/login
      MS_AUTH_REDIRECT_PATH: /microsoft/redirect
    expose:
      - *auth_port
    secrets:
      - source: db_auth_user_password
        uid: "10001"
      - source: db_name
        uid: "10001"
      - source: ms_auth_client_id
        uid: "10001"
      - source: ms_auth_client_credential
        uid: "10001"
    healthcheck:
      # TODO: interpolate *auth_port instead of hardcoding 8000
      test: curl http://localhost:8000/health || exit 1
      interval: 5s
      start_period: 10s
      start_interval: 1s
      timeout: 5s
      retries: 10
  scamplers-frontend:
    restart: always
    build:
      context: typescript/scamplers-frontend
      args:
        NODE_VERSION: 23.11.0
      target: build
    environment:
        PORT: &frontend_port 8000
        BACKEND_HOST: *backend_host
        BACKEND_PORT: *backend_port
    # depends_on:
    #   scamplers-backend:
    #     condition: service_healthy
    #   scamplers-auth:
    #     condition: service_healthy
    # This healthcheck will be good for a proper server as well
    # healthcheck:
    #   test: [CMD, curl, "http://localhost:$PORT/health"]
    #   interval: 5s
    #   start_period: 5s
    #   start_interval: 1s
    #   timeout: 1s
    #   retries: 5
    volumes:
      - scamplers-frontend:/opt/scamplers-frontend
  caddy:
    image: caddy:2.9.1-alpine
    environment:
      PUBLIC_URL: ${SCAMPLERS_PUBLIC_URL}
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy:/etc/caddy
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      scamplers-auth:
        condition: service_healthy
volumes:
  db-data:
  logs:
  caddy-data:
  caddy-config:
  scamplers-frontend:
secrets:
  db_root_user:
    environment: SCAMPLERS_DB_ROOT_USER
  db_root_password:
    environment: SCAMPLERS_DB_ROOT_PASSWORD
  db_login_user_password:
    environment: SCAMPLERS_DB_LOGIN_USER_PASSWORD
  auth_secret:
    environment: SCAMPLERS_AUTH_SECRET
  db_name:
    environment: SCAMPLERS_DB_NAME
  ms_auth_client_id:
    environment: SCAMPLERS_MS_AUTH_CLIENT_ID
  ms_auth_client_credential:
    environment: SCAMPLERS_MS_AUTH_CLIENT_CREDENTIAL
  seed_data:
    file: ${SCAMPLERS_SEED_DATA}
