services:
  db:
    image: postgres:${SCAMPLERS_POSTGRES_VERSION}-alpine${SCAMPLERS_ALPINE_VERSION}
    restart: always
    user: postgres
    secrets:
      - db_root_user
      - db_root_password
      - db_name
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_root_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    expose:
      - 5432
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 2s
      timeout: 5s
      retries: 10
  scamplers:
    build:
      args:
        ALPINE_VERSION: ${SCAMPLERS_ALPINE_VERSION}
        RUST_VERSION: ${SCAMPLERS_RUST_VERSION}
      context: rust
      target: final
    ports:
      - ${SCAMPLERS_APP_PORT}:${SCAMPLERS_APP_PORT}
    secrets:
      - db_root_user
      - db_root_password
      - db_login_user_password
      - db_host
      - db_port
      - db_name
      - auth_host
      - auth_port
      - ms_auth_path
      - app_host
      - app_port
      - seed_data
    volumes:
      - logs:/logs
    depends_on:
      db:
        condition: service_healthy
  scamplers-auth:
    build:
      args:
        PYTHON_VERSION: ${SCAMPLERS_PYTHON_VERSION}
      context: python/scamplers-auth
      target: final
    ports:
      - ${SCAMPLERS_AUTH_PORT}:${SCAMPLERS_AUTH_PORT}
    secrets:
      - auth_host
      - auth_port
      - ms_auth_path
      - ms_auth_client_id
      - ms_auth_client_credential
      - ms_auth_redirect_uri
    volumes:
      - logs:/logs
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
  logs:
# For simplicity, our entire configuration is loaded as secrets. That way, we don't have to grab some values from the environment and others from the secrets dir
secrets:
  db_root_user:
    environment: SCAMPLERS_DB_ROOT_USER
  db_root_password:
    environment: SCAMPLERS_DB_ROOT_PASSWORD
  db_login_user_password:
    environment: SCAMPLERS_DB_LOGIN_USER_PASSWORD
  db_host:
    environment: SCAMPLERS_DB_HOST
  db_port:
    environment: SCAMPLERS_DB_PORT
  db_name:
    environment: SCAMPLERS_DB_NAME
  auth_host:
    environment: SCAMPLERS_AUTH_HOST
  auth_port:
    environment: SCAMPLERS_AUTH_PORT
  ms_auth_path:
    environment: SCAMPLERS_MS_AUTH_PATH
  ms_auth_client_id:
    environment: SCAMPLERS_MS_AUTH_CLIENT_ID
  ms_auth_client_credential:
    environment: SCAMPLERS_MS_AUTH_CLIENT_CREDENTIAL
  ms_auth_redirect_uri:
    environment: SCAMPLERS_MS_AUTH_REDIRECT_URI
  app_host:
    environment: SCAMPLERS_APP_HOST
  app_port:
    environment: SCAMPLERS_APP_PORT
  seed_data:
    file: ${SCAMPLERS_SEED_DATA}
