services:
  db:
    build:
      context: db
      args:
        POSTGRES_VERSION: ${SCAMPLERS_POSTGRES_VERSION}
        ALPINE_VERSION: ${SCAMPLERS_ALPINE_VERSION}
    restart: always
    user: root
    secrets:
      - db_root_user
      - db_root_password
      - db_login_user_password
      - db_auth_user_password
      - db_name
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_root_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    expose:
      - 5432
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 2s
      timeout: 5s
      retries: 10
  scamplers-web:
    build:
      context: typescript/scamplers-web
      args:
        NODE_VERSION: ${SCAMPLERS_NODE_VERSION}
      target: build
    volumes:
      - scamplers-web_build:/opt/scamplers-web
  scamplers:
    build:
      args:
        ALPINE_VERSION: ${SCAMPLERS_ALPINE_VERSION}
        RUST_VERSION: ${SCAMPLERS_RUST_VERSION}
      context: .
      dockerfile: rust/Dockerfile
      target: final
    ports:
      - ${SCAMPLERS_APP_PORT}:${SCAMPLERS_APP_PORT}
    healthcheck:
      test:
        - CMD
        - curl
    secrets:
      - source: db_root_user
        uid: "10001"
      - source: db_root_password
        uid: "10001"
      - source: db_login_user_password
        uid: "10001"
      - source: db_host
        uid: "10001"
      - source: db_port
        uid: "10001"
      - source: db_name
        uid: "10001"
      - source: auth_host
        uid: "10001"
      - source: auth_port
        uid: "10001"
      - source: ms_auth_path
        uid: "10001"
      - source: app_host
        uid: "10001"
      - source: app_port
        uid: "10001"
      - source: seed_data
        uid: "10001"
      - source: session_id_salt_string
        uid: "10001"
    volumes:
      - logs:/logs
      - scamplers-web_build:/opt/scamplers-web
    depends_on:
      db:
        condition: service_healthy
      scamplers-web:
        condition: service_completed_successfully
  scamplers-auth:
    build:
      args:
        PYTHON_VERSION: ${SCAMPLERS_PYTHON_VERSION}
      context: python/scamplers-auth
      target: final
    depends_on:
      scamplers:
        condition: service_healthy
    ports:
      - ${SCAMPLERS_AUTH_PORT}:${SCAMPLERS_AUTH_PORT}
    secrets:
      - source: db_auth_user_password
        uid: "10001"
      - source: db_host
        uid: "10001"
      - source: db_port
        uid: "10001"
      - source: db_name
        uid: "10001"
      - source: auth_host
        uid: "10001"
      - source: auth_port
        uid: "10001"
      - source: ms_auth_path
        uid: "10001"
      - source: ms_auth_client_id
        uid: "10001"
      - source: ms_auth_client_credential
        uid: "10001"
      - source: ms_auth_redirect_url
        uid: "10001"
      - source: session_id_salt_string
        uid: "10001"
    volumes:
      - logs:/logs
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
  logs:
  scamplers-web_build:
# For simplicity, our entire configuration is loaded as secrets. That way, we don't have to grab some values from the environment and others from the secrets dir
secrets:
  db_root_user:
    environment: SCAMPLERS_DB_ROOT_USER
  db_root_password:
    environment: SCAMPLERS_DB_ROOT_PASSWORD
  db_login_user_password:
    environment: SCAMPLERS_DB_LOGIN_USER_PASSWORD
  db_auth_user_password:
    environment: SCAMPLERS_DB_AUTH_USER_PASSWORD
  db_host:
    environment: SCAMPLERS_DB_HOST
  db_port:
    environment: SCAMPLERS_DB_PORT
  db_name:
    environment: SCAMPLERS_DB_NAME
  auth_host:
    environment: SCAMPLERS_AUTH_HOST
  auth_port:
    environment: SCAMPLERS_AUTH_PORT
  ms_auth_path:
    environment: SCAMPLERS_MS_AUTH_PATH
  ms_auth_client_id:
    environment: SCAMPLERS_MS_AUTH_CLIENT_ID
  ms_auth_client_credential:
    environment: SCAMPLERS_MS_AUTH_CLIENT_CREDENTIAL
  ms_auth_redirect_url:
    environment: SCAMPLERS_MS_AUTH_REDIRECT_URL
  app_host:
    environment: SCAMPLERS_APP_HOST
  app_port:
    environment: SCAMPLERS_APP_PORT
  seed_data:
    file: ${SCAMPLERS_SEED_DATA}
  session_id_salt_string:
    environment: SCAMPLERS_SESSION_ID_SALT_STRING
