{
  "services":
    {
      "db":
        {
          "image": "postgres:17",
          "restart": "always",
          "user": "postgres",
          "secrets": ["db-root-password"],
          "volumes": ["db-data:/var/lib/postgresql/data"],
          "environment":
            [
              "POSTGRES_USER_FILE=/run/secrets/db-root-username",
              "POSTGRES_PASSWORD_FILE=/run/secrets/db-root-password",
              "POSTGRES_DB_FILE=/run/secrets/db-name",
              "POSTGRES_HOST_AUTH_METHOD=scram-sha-256",
            ],
          "expose": [5432],
          "healthcheck":
            {
              "test": ["CMD", "pg_isready"],
              "interval": "2s",
              "timeout": "5s",
              "retries": 10,
            },
        },
      "scamplers":
        {
          "build": { "context": "rust/scamplers", "target": "final" },
          "ports": ["8000:8000"],
          "secrets":
            [
              "scamplers-config",
              "db-root-username",
              "db-root-password",
              "db-name",
            ],
          "volumes": ["logs:/logs"],
          "depends_on": { "db": { "condition": "service_healthy" } },
        },
      "scamplers-auth":
        {
          "build": { "context": "python/scamplers-auth", "target": "final" },
          "ports": ["8001:8001"],
          "secrets": ["auth-config"],
          "volumes": ["logs:/logs"],
          "depends_on": { "db": { "condition": "service_healthy" } },
        },
    },
  "volumes": { "db-data": null, "logs": null },
  "secrets":
    {
      "auth-config": { "file": "${AUTH_CONFIG_PATH}" },
      "scamplers-config": { "file": "${SCAMPLERS_CONFIG_PATH}" },
      "db-root-username": { "environment": "SCAMPLERS_DB_ROOT_USERNAME" },
      "db-root-password": { "environment": "SCAMPLERS_DB_ROOT_PASSWORD" },
      "db-name": { "environment": "SCAMPLERS_DB_NAME" },
    },
}
