imports_granularity = "Crate"
group_imports = "StdExternalCrate"
wrap_comments = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
reorder_impl_items = true
use_field_init_shorthand = true