[project]
name = "scamplers-auth"
version = "0.1.0"
description = ""
authors = [
    {name = "Ahmed Said",email = "ahmed.said@jax.org"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "msal (>=1.31.1,<2.0.0)",
    "sanic (>=24.12.0,<25.0.0)",
    "fire (>=0.7.0,<0.8.0)",
    "pydantic (>=2.10.6,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
