/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SpecimenMeasurement = {
  measured_by: PersonStub;
  [k: string]: unknown;
} & SpecimenMeasurement1;
export type SpecimenMeasurement1 =
  | {
      instrument_name: string;
      measured_at: string;
      quantity: "RIN";
      value: number;
      [k: string]: unknown;
    }
  | {
      instrument_name: string;
      measured_at: string;
      quantity: "DV200";
      value: number;
      [k: string]: unknown;
    }
  | {
      quantity: "UNKNOWN";
      [k: string]: unknown;
    };
export type Species =
  | "ambystoma_mexicanum"
  | "canis_familiaris"
  | "drosophila_melanogaster"
  | "gasterosteus_aculeatus"
  | "homo_sapiens"
  | "mus_musculus"
  | "rattus_norvegicus"
  | "sminthopsis_crassicaudata"
  | "unknown";

export interface Specimen {
  embedded_in?: string | null;
  id: string;
  lab: LabStub;
  measurements?: SpecimenMeasurement[] | null;
  name: string;
  notes?: string[] | null;
  preserved_with?: string | null;
  received_at: string;
  returned_at?: string | null;
  species: Species[];
  tissue: string;
  type: string;
  [k: string]: unknown;
}
export interface LabStub {
  id: string;
  link: string;
  name: string;
  [k: string]: unknown;
}
export interface PersonStub {
  id: string;
  link: string;
  name: string;
  [k: string]: unknown;
}
