/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdatedInstitution {
  id: string;
  ms_tenant_id?: string | null;
  name?: string | null;
  [k: string]: unknown;
}
