[workspace]
resolver = "2"
members = ["build-scamplers", "scamplers"]
default-members = ["scamplers"]

[workspace.dependencies]
camino = { version = "1.1.9", features = ["serde1"] }
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
uuid = { version = "1.16.0", features = ["serde", "v7", "v4"] }
serde = { version = "1.0.219", features = ["derive"] }
regex = "1.11.1"
csv = "1.3.1"
bytes = "1.10.1"
reqwest = { version = "0.12.14", default-features = false, features = [
    "rustls-tls",
    "http2",
    "charset",
    "json",
] }
url = { version = "2.5.4", features = ["serde"] }
clap = { version = "4.5.32", features = ["derive", "env"] }
anyhow = "1.0.97"
axum = { version = "0.8.1", default-features = false, features = [
    "http2",
    "json",
    "macros",
    "query",
    "tokio",
] }
axum-extra = { version = "0.10.0", features = ["query", "typed-header"] }
serde_json = { version = "1.0.140", features = ["arbitrary_precision"] }
diesel = { version = "2.2.8", default-features = false, features = [
    "without-deprecated",
    "chrono",
    "uuid",
    "serde_json",
] }
chrono = { version = "0.4.40", features = ["serde"] }
futures = { version = "0.3.31" }
diesel_migrations = { version = "2.2.0", features = ["postgres"] }
diesel-async = { version = "0.5.2", features = [
    "postgres",
    "deadpool",
    "async-connection-wrapper",
] }
tracing-appender = "0.2.3"
tracing = { version = "0.1.41", features = ["valuable"] }
tower = { version = "0.5.2", default-features = false }
tracing-subscriber = { version = "0.3.19", features = ["json"] }
valuable = { version = "0.1.1", features = ["derive"] }
argon2 = "0.5.3"
garde = { version = "0.22.0", features = ["derive", "email", "serde", "regex"] }
toml = { version = "0.8.20" }
testcontainers-modules = { version = "0.11.6", features = ["postgres"] }
schemars = { version = "0.8.22", features = ["chrono", "uuid1"] }
tower-http = { version = "0.6.2", features = ["trace"] }
rand = "0.9.0"
strum = { version = "0.27.1", features = ["derive"] }
heck = "0.5.0"
scraper = { version = "0.23.1", features = ["serde"] }
pretty_assertions = "1.4.1"
rstest = "0.24.0"
similar = "2.7.0"
dotenvy = { version = "0.15.7" }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
