[package]
name = "scamplers"
version = "0.1.0"
edition = "2024"
authors = ["Ahmed Said <ahmed.said@jax.org>"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "scamplers"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3 = { version = "0.23.4", features = ["chrono", "abi3"] }
camino = { version = "1.1.9", features = ["serde1"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.12.1", features = ["serde", "v7", "v4"] }
serde = { version = "1.0.217", features = ["derive"] }
regex = "1.11.1"
csv = "1.3.1"
bytes = "1.9.0"
reqwest = { version = "0.12.12", default-features = false, features = ["rustls-tls", "http2", "charset", "json"] }
url = { version = "2.5.4", features = ["serde"] }
clap = { version = "4.5.27", features = ["derive"] }
anyhow = "1.0.95"
axum = { version = "0.8.1", default-features = false, features = ["http2", "json", "macros", "query", "tokio"] }
axum-extra = { version = "0.10.0", features = ["query"] }
serde_json = { version = "1.0.137", features = ["arbitrary_precision"] }
diesel = {version = "2.2.7", default-features = false, features = ["without-deprecated", "chrono", "uuid", "serde_json"]}
chrono = { version = "0.4.39", features = ["serde"]}
futures = {version = "0.3.31" }
diesel_migrations ={ version = "2.2.0", features = ["postgres"]}
diesel-async = { version = "0.5.2", features = ["postgres", "deadpool", "async-connection-wrapper"] }
tracing-appender = "0.2.3"
tracing = { version = "0.1.41", features = ["valuable"]}
tower = { version = "0.5.2", default-features = false }
strum = {version = "0.26.3", default-features = false, features = ["derive"]}
tracing-subscriber = {version = "0.3.19", features = ["json"]}
valuable = { version = "0.1.1", features = ["derive"] }
argon2 = "0.5.3"
garde = { version = "0.22.0", features = ["derive", "email", "serde"] }
toml = { version = "0.8.20", default-features = false, features = ["parse"] }
testcontainers-modules = { version = "0.11.5", features = ["postgres"], optional = true}

[features]
dev-or-test = ["testcontainers-modules"]

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.24.0"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
