// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DualIndexSet = { name: string, kit: string, well: string, index_i7: string, index2_workflow_a_i5: string, index2_workflow_b_i5: string, };

export type SingleIndexSet = { name: string, kit: string, well: string, sequences: Array<string>, };
