// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Institution = { id: string, name: string, link: string, };

export type NewInstitution = { name: string, ms_tenant_id: string | null, };

export type UpdatedInstitution = { id: string, name: string | null, ms_tenant_id: string | null, };
