// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Institution } from "./institution";

export type Person = { institution: Institution, id: string, name: string, email: string, orcid: string | null, };

export type PersonFilter = { ids: Array<string>, name: string | null, email: string | null, };

export type UserRole = "admin" | "computational_staff" | "lab_staff";
