# # Adapted from
# name: Build scamplers-backend

# on:
#   push:
#     branches:
#       - main
#   workflow_run:
#     workflows:
#       - rust.yml

# env:
#   IMAGE_NAME: scamplers-backend
#   COMPOSE_BAKE: "true"
#   REGISTRY: ghcr.io

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       packages: write
#       attestations: write
#       id-token: write

#     steps:
#       - name: Checkout repository code
#         uses: actions/checkout@v4

#       - name: Build image
#         run: docker compose build scamplers-backend

#       - name: Log in to registry
#         uses: docker/login-action@v3
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Extract metadata
#         id: metadata
#         uses: docker/metadata-action@v5
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

#       - name: Push image
#         run: |
#           IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
#           VERSION=$(cd rust/scamplers-backend && cargo pkgid | cut -d '#' -f2)
#           docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
#           docker push $IMAGE_ID:$VERSION
