name: check Rust code
on:
  push:
    paths:
      - rust/**

jobs:
  check-rust:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache cargo-generated files
        uses: Swatinem/rust-cache@v2
        id: cache-cargo

      - name: Install diesel
        run: cargo install diesel_cli --no-default-features --features postgres

      - name: Install nightly toolchain
        run: rustup toolchain install nightly && rustup component add --toolchain nightly rustfmt

      - name: Check code
        run: |
          cd rust
          cargo +nightly fmt -- --check
          RUSTFLAGS="--cfg tracing_unstable" cargo build --workspace
          RUSTFLAGS="--cfg tracing_unstable" cargo clippy --workspace --exclude scamplers-schema
          RUSTFLAGS="--cfg tracing_unstable" cargo test --workspace
