name: Check Rust Code
on:
  push:
    paths:
      - rust/**

jobs:
  check-rust:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings --cfg tracing_unstable

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2

      - name: Install diesel
        run: cargo install diesel_cli --no-default-features --features postgres

      - name: Install nightly toolchain
        run: rustup toolchain install nightly && rustup component add --toolchain nightly rustfmt

      - name: Format
        working-directory: rust
        run: cargo +nightly fmt -- --check

      - name: Build
        working-directory: rust
        run: cargo build --package scamplers-backend

      - name: Lint
        working-directory: rust
        run: cargo clippy --workspace --exclude scamplers-schema

      - name: Test
        working-directory: rust
        run: ./test.sh

      - name: Compare typescript/scamplers-core/rust-src to rust/scamplers-core/src
        run: diff --recursive typescript/scamplers-core/rust-src rust/scamplers-core/src
