name: check TypeScript code

on:
  push:
    paths:
      - typescript/**

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run tests
        run: cd typescript/scamplers-frontend && npm run test

  lint_code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Lint code
        run: cd typescript/scamplers-frontend && npm run lint

  check_typing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check typing
        run: cd typescript/scamplers-frontend && npm run check
