name: Check TypeScript Code
on:
  push:
    paths:
      - typescript/**

jobs:
  check-typescript:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: typescript/scamplers-frontend
        run: npm install

      - name: Lint
        working-directory: typescript/scamplers-frontend
        run: npm run lint

      - name: Svelte check
        working-directory: typescript/scamplers-frontend
        run: npm run check

      - name: Unit test
        working-directory: typescript/scamplers-frontend
        run: npm run test:unit -- --run
