name: check TypeScript code

on:
  push:
    paths:
      - typescript/**

jobs:
  check-typescript:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd typescript/scamplers-frontend && npm install

      - name: Check code
        run: |
          cd typescript/scamplers-frontend
          npm run lint
          npm run check
          npm run test
